Cancel triggered build on InterruptException
With 2.44, and while used in a post build script, when the parent job is
cancelled, while the downstream job is waiting to be started, we get an
unhandled InterruptException at waitForStart().

Catch InterruptException while waitingForStart and properly cancel the
build.

Stacktrace (with 2.44):

org.jenkinsci.plugins.postbuildscript.PostBuildScriptException: java.lang.InterruptedException
    at org.jenkinsci.plugins.postbuildscript.processor.Processor.processBuildSteps(Processor.java:190)
    at org.jenkinsci.plugins.postbuildscript.processor.Processor.processScripts(Processor.java:91)
    at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:79)
    at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:73)
    at org.jenkinsci.plugins.postbuildscript.PostBuildScript.perform(PostBuildScript.java:116)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:803)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:752)
    at hudson.model.Build$BuildExecution.post2(Build.java:177)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:697)
    at hudson.model.Run.execute(Run.java:1932)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:97)
    at hudson.model.Executor.run(Executor.java:429)
Caused by: java.lang.InterruptedException
    at java.base/java.lang.Object.wait(Native Method)
    at java.base/java.lang.Object.wait(Object.java:328)
    at hudson.remoting.AsyncFutureImpl.get(AsyncFutureImpl.java:79)
    at hudson.model.queue.FutureImpl.waitForStart(FutureImpl.java:68)
    at hudson.plugins.parameterizedtrigger.TriggerBuilder.perform(TriggerBuilder.java:146)
    at org.jenkinsci.plugins.postbuildscript.processor.Processor.processBuildSteps(Processor.java:180)
    ... 13 more

https://phabricator.wikimedia.org/T282893